name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  # Pruebas
  tests:
    name: Pruebas (Unitarias & Integración)
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./backend

    steps:
    - name: Descargar código (Checkout)
      uses: actions/checkout@v3

    - name: Configurar Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Instalar dependencias
      run: npm install

    - name: Ejecutar pruebas
      run: npm test
  
  # Despliegue
  deploy:
    name: Build & Push a Docker Hub
    needs: tests
    runs-on: ubuntu-latest

    # Solo corre si es la rama main (evita correr en Pull Requests)
    if: github.ref == 'refs/heads/main'

    defaults:
      run:
        working-directory: ./backend
    
    steps:
    - name: Descargar código (Checkout)
      uses: actions/checkout@v3

    - name: Login en Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Construir y Subir Imagen Docker
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/tecno-repuestos:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/tecno-repuestos:latest